// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BodyBackground: typeof import('./../src/test/bodyBackground.vue')['default']
    Head: typeof import('./../src/layout/Head.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    ImgReader: typeof import('./../src/components/ImgReader/ImgReader.vue')['default']
    Layout: typeof import('./../src/layout/Layout.vue')['default']
    Main: typeof import('./../src/layout/Main.vue')['default']
    Nav: typeof import('./../src/layout/Nav.vue')['default']
    Tester: typeof import('./../src/test/tester.vue')['default']
    ToolBar: typeof import('./../src/components/ToolBar/ToolBar.vue')['default']
  }
}

export { }
